name: Release specific project/tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag (e.g., v1.2.3)"
        required: true
      version:
        description: "Scalameta version (e.g., 1.2.3)"
        required: true
      project:
        description: "Project name (e.g., trees)"
        required: true
      platform:
        description: "Platform name (JS, JVM, Native)"
        required: true
      scala:
        description: "Scala version (2.13 etc.)"
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out tag ${{ github.event.inputs.tag }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
      - uses: olafurpg/setup-scala@v14
      - name: Set up JVM
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Publish ${{ github.event.inputs.project }} to Sonatype
        run: sbt -Dscalameta.version=${{ github.event.inputs.version }} ci-release
        env:
          CI_COMMIT_TAG: ${{ github.event.inputs.tag }}
          CI_RELEASE: ${{ github.event.inputs.scala != '' && concat('++', github.event.inputs.scala, ' ') || '+' }}${{ github.event.inputs.project }}${{ github.event.inputs.platform }}/publishSigned
          SCALAMETA_PLATFORM: ${{ github.event.inputs.platform }}
          GIT_USER: scalameta@scalameta.org
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
